spring.application.name=SpringOath2
server.port=8000

# Remove the "your-client-id=" and "your-client-secret=" text
spring.security.oauth2.client.registration.google.client-id=953584122342-a5945428ot2ccje4rrc6j1aho9lim632.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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


# Remove the "your-client-id=" and "your-client-secret=" text
spring.security.oauth2.client.registration.github.client-id=Ov23liGZrc48btGgJP84
spring.security.oauth2.client.registration.github.client-secret=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
