spring.application.name=SpringOath2
server.port=8000

# Remove the "your-client-id=" and "your-client-secret=" text
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Remove the "your-client-id=" and "your-client-secret=" text
spring.security.oauth2.client.registration.github.client-id=Ov23liGZrc48btGgJP84
spring.security.oauth2.client.registration.github.client-secret=d188b70ce96d76f46d441a1f01c4c701d6893620
